<?php
/**
 * @file
 * Code for the Core Application Feature feature.
 */

include_once 'core_application_feature.features.inc';

/**
 * Implements hook_node_view().
 */
function core_application_feature_node_view($node, $view_mode, $langcode) {
    if ($node -> type == 'paleoscan_overview' && $view_mode == "full"){

        // Load the view of core application menu
        $view_menu_core = views_embed_view('products', 'attachment_4');

        // Load the view of core add-on menu
        $view_menu_addon = views_embed_view('products', 'attachment_5');

        // Create the wrapper
        $wrapper = entity_metadata_wrapper('node', $node);

        // Set the value to field with the good format
        $wrapper->field_core_application_menu->set(array("value" => $view_menu_core,"format" => "full_html"));
        $wrapper->field_add_on_menu->set(array("value" => $view_menu_addon,"format" => "full_html"));

        // Save the wrapper
        $wrapper->save();

    }

}