<?php
/**
 * @file
 * Code for the Feature_eliis_basic_page feature.
 */

include_once 'feature_eliis_basic_page.features.inc';

/**
 * Implements hook_node_view().
 * Utilisation de content et d'un extra_field
 */
function feature_eliis_basic_page_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'page') {
    //dpm($node);
    $settings = field_extra_fields_get_display('node',$node->type,$view_mode);
    if($settings["extra_field_customers"]['visible'] &&
      $node->content['field_eliis_customers']['#items'][0]['value']){
      $node->content["extra_field_customers"] = array(
        '#prefix' => '<div class="row"><div class="col-md-6">',
        "#markup" => views_embed_view('partenaires', 'block_partner_one'),
        '#suffix' => '</div>',
      );
    }
    if($settings["extra_field_academics"]['visible'] &&
      $node->content['field_eliis_academic']['#items'][0]['value']){
      $node->content["extra_field_academics"] = array(
        '#prefix' => '<div class="col-md-6">',
        "#markup" => views_embed_view('partenaires', 'block_partner_two'),
        '#suffix' => '</div></div>',
      );
    }
  }

}

/**
 * Implements hook_field_extra_fields().
 */
function feature_eliis_basic_page_field_extra_fields() {
  $extra['node']['page'] = array(
    'display' => array(
      'extra_field_customers' => array(
        'label' => t('Customers (extra)'),
        'weight' => 0,
      ),
      'extra_field_academics' => array(
        'label' => t('Academic partners (extra)'),
        'weight' => 0,
      ),
    )
  );

  return $extra;
}
