<?php
/**
 * @file
 * Code for the FeatureDiapoBio feature.
 */

include_once 'featurediapobio.features.inc';

/*function featurediapobio_views_pre_render(&$view)
{
   //dpm($view);
   if (($view->name == 'diaporama' && $view->current_display == 'block_slideshow_home')) {
       foreach ($view->result as &$value) {

           //Test if an url target is specified
           if (sizeof($value->field_field_url[0]['rendered']['#markup']) > 0){

               dpm($value->field_field_diapo_image);
           }
       }
   }
}
/*   //dpm($view);
   /*if (($view->name == 'events' && $view->current_display == 'page') || ($view->name == 'events' && $view->current_display == 'block_evenements_home')) {
       foreach ($view->result as &$value) {

//Test if an url target is specified
           if (sizeof($value->field_field_event_url_target) > 0) {

               $begin_http = preg_match("#^http|https(.*)$#i", $value->field_field_event_url_target[0]['rendered']['#markup']);
               $custom_url = $begin_http ? $value->field_field_event_url_target[0]['rendered']['#markup'] : 'http://'.$value->field_field_event_url_target[0]['rendered']['#markup'];
               $target = (empty($value->field_field_event_new_window) || !$value->field_field_event_new_window[0]['raw']['value'])? '' : ' target="_blank" ';
               /*if (sizeof($value->field_field_event_image) > 0) {
                 $value->field_field_event_image[0]['rendered']['#markup'] = '<a '.$target.' href="'.$custom_url.'">'.$value->field_field_event_image[0]['rendered']['#markup'].'</a>';
               }*/
                /*$value->field_field_event_url_target[0]['rendered']['#markup'] = '<h3 class="title-event-list"><a '.$target.' href="'.$custom_url.'">'.$value->node_title.'</a></h3>';
            }else {
                $href = ' href="'.drupal_get_path_alias("node/".$value->nid).'" ';
                $value->field_field_event_url_target[0]['rendered']['#markup'] = '<h3 class="title-event-list"><a href="/node/'.$value->nid.'">'.$value->node_title.'</a></h3>';
                /*if (sizeof($value->field_field_event_image) > 0) {
                  $value->field_field_event_image[0]['rendered']['#markup'] = '<a '.$href.'>'.$value->field_field_event_image[0]['rendered']['#markup'].'</a>';
                }
            }
        }

    }
} */
