<?php
/**
 * @file
 * Code for the Feature licencied feature.
 */

include_once 'feature_licencied.features.inc';

/**
 * Implements hook_permission().
 */
function feature_licencied_permission() {
  return array(
    "access licensed files" => array(
      "title" => "Access licensed files",
    ),
  );
}

/**
 * Implements hook_file_download().
 */
function feature_licencied_file_download($uri) {
  if (strpos($uri, "private://licensed/") === 0) {
    if (!user_access("access licensed files")) {
      return -1;
    }
    $files = file_load_multiple(array(), array("uri" => $uri));
    if (empty($files)) {
      return -1;
    }
    $file = reset($files);
    return file_get_content_headers($file);
  }
}

/**
 * Implements hook_menu_alter().
 */
function feature_licencied_menu_alter(&$items){
    $items['user/register']['page callback'] = 'feature_licencied_ask_account';
}

function feature_licencied_ask_account(){
    drupal_goto('/node/17/');
}

/**
 * Implements hook_field_collection_item_view().
 */
function feature_licencied_field_collection_item_view($field_collection_item, $view_mode, $langcode) {
  if ($field_collection_item->field_name == 'field_files_to_download'
    && isset($field_collection_item->content['field_color_link_download'][0]['#markup'])){
    $color = $field_collection_item->content['field_color_link_download'][0]['#markup'];
    unset($field_collection_item->content['field_color_link_download']);
    if ($color == 'red'){
      $field_collection_item->content['field_sofware'][0]['#prefix']= '<div class="red-download">';
      $field_collection_item->content['field_sofware'][0]['#suffix']= '</div>';
    }
  }

}
